on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
#  push:
#   tags:
#     - '*'
  pull_request_target:
    branches:
      - main
    paths-ignore:
      - '**.md'
    types: [closed]
#  pull_request_review:
#    types:
#      - submitted
  # Also trigger on page_build, as well as release created events
  #page_build:
  #release:
  #  types: # This configuration does not affect the page_build event above
  #  - created
jobs:
  tag:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    outputs:
      name: ${{ steps.generate_tag.outputs.name }}
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Generate tag name
        id: generate_tag
        #run: echo "::set-output name=name::v$(date -d "$(git show -s --format=%ci)" +'%Y.%-m.%-d')"
        run: echo "::set-output name=name::v1.1.4"
  build:
    name: build-fortiweb-ingress
    needs: [tag]
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - uses: actions/checkout@v2
      - name: tagging
        run: | 
          git config user.name "yslee"
          git config user.email yslee@fortinet.com
          git tag "${{ needs.tag.outputs.name }}" -m "Version:${{ needs.tag.outputs.name }}"
      #- name: Create Release
      #  id: create_release
      #  uses: actions/create-release@latest
      #  env:
      #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #  with:
      #    tag_name: ${{needs.tag.outputs.name}}
      #    release_name: Release ${{needs.tag.outputs.name}}
      #    body: "FortiWeb Ingress Release"
      #    draft: false
      #    prerelease: false
      - name: create release package
        run: tar zcvf ./fortiweb-ingress.tar.gz ./*
      - name: upload release package
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{secrets.GITHUB_TOKEN}}
          release_name: Release ${{needs.tag.outputs.name}}
          file: ./fortiweb-ingress.tar.gz
          asset_name: fortiweb-ingress.tar.gz
          tag: ${{needs.tag.outputs.name}}
          overwrite: true
          body: "FortiWeb Ingress Release"
